
name: Deploy static content to Pages

on:

  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
    
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'
      
      - name: Install dependencies and zip Lambda function
        run: |
          mkdir -p package
          cp lambda_function.py package/
          cd package
          zip -r ../lambda_function.zip .
          cd ..
      
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7
          terraform_wrapper: false
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Terraform Init
        run: terraform init
        
      - name: Terraform Validate
        run: terraform validate
      
      - name: Terraform Plan
        run: |
          terraform plan \
            -var="aws_region=${{ secrets.AWS_REGION }}" \
            -var="your_email=${{ secrets.MY_EMAIL }}" 
            
      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: |
          terraform apply -auto-approve \
            -var="aws_region=${{ secrets.AWS_REGION }}" \
            -var="your_email=${{ secrets.MY_EMAIL }}"

      - name: Apply API Gateway url to html
        run: |
          # Get the URL from Terraform output
          URL=$(terraform output -raw api_gateway_url 2>&1 | \
                grep -oP 'https?://[^\s::]*' | \
                head -n 1 | \
                tr -d '\n')

          echo "API Gateway URL is: $URL"
          # Replace the placeholder in index.html
          sed -i "s|__API_GATEWAY_URL__|$URL|g" index.html

      - name: Create pages folder
        run: |
          mkdir -p gh-pages
          mkdir -p gh-pages/images
          cp index.html gh-pages/
          cp Resume.pdf gh-pages/
          cp images/* gh-pages/images/

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: gh-pages

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

      - name: Print GitHub Pages URL
        run: |
          echo "🚀 GitHub Pages deployed successfully!"
          echo "📄 Your site is available at: https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}"
          cat index.html | grep 'fetch('