
name: Deploy static content to Pages

on:

  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
    
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      
      - name: Install dependencies and zip Lambda function
        run: |
          mkdir -p package
          cp lambda_function.py package/
          cd package
          zip -r ../lambda_function.zip .
          cd ..

      - name: Lambda Deploy
        uses: appleboy/lambda-action@v0.2.0
        with:
          function_name: contact-form-handler
          zip_file: lambda_function.zip
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Apply API Gateway url to html
        run: |
          # Get the URL from Terraform output
          URL=$(aws apigatewayv2 get-apis --query "Items[?Name=='contact-form-http-api'].ApiEndpoint | [0]" --output text)
          sed -i "s|__API_GATEWAY_URL__|$URL|g" index.html

      - name: Create pages folder
        run: |
          mkdir -p gh-pages
          mkdir -p gh-pages/images
          cp index.html gh-pages/
          cp Resume.pdf gh-pages/
          cp images/* gh-pages/images/

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: gh-pages

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

      - name: Print GitHub Pages URL
        run: |
          echo "🚀 GitHub Pages deployed successfully!"
          echo "📄 Your site is available at: https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}"
          cat index.html | grep 'fetch('